name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ ubuntu-22.04, macos-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: khlopko/setup-swift@bfd61cbd14eeef55a27afc45138b61ced7174839
        with:
          swift-version: "main-snapshot"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: swift test

